### ISSUE TITLE
Add loader

### ISSUE THREAD

**Issue by kjugi** [SnowdogApps/magento2-vue-checkout#26]
Add loader when clicking on the button or when loading/updating some data.

+ When changing step
+ When loading i.e methods

**Comment by kjugi** [comment]
Must think about the new method of calling loader. Don't want to manually change `this.$store.state.loader` each time. Must think about maybe some eventListener on specific elements and toggle this action or sth 🤔

**Comment by kjugi** [comment]
And think about storing styles. For now, in the loader, I have `<style>` tag.

**Comment by szafran89** [comment]
Good approach it would be to write mutation `setLoading (state, payload)` and commit it `commit('setLoading', true|false)` when you make async requests inside store actions.

**Comment by kjugi** [comment]
As I wrote in my first PR to loader in buttons:
If we want to add loader on start than must deal with v-cloak and add some styles to loader
