### ISSUE TITLE
Add support to step Back button

### ISSUE THREAD

**Issue by kjugi** [SnowdogApps/magento2-vue-checkout#29]
Add support to step back Button b/c, for now, it only exists. 

Major idea is to back to the previous step with selected/filled data from Vuex store.

When will end it can think about the final step and fill 'Go to product' link if it will be possible.

**Comment by szafran89** [comment]
We can consider this component.

**Comment by kjugi** [comment]
This issue it outdated. For now we are storing data in vuex and we have selected/filled data when going back to prev button
