### ISSUE TITLE
Success step

### ISSUE THREAD

**Issue by kjugi** [SnowdogApps/magento2-vue-checkout#61]
Do some actions in success step. Maybe show some related product instead of text `We did it!` and button with back to the random category.

**Comment by szafran89** [comment]
@kjugi For now there is also order number. IMO we don't need related product on success page. 
All what we need is to do the same view as on Magento success page (screen below).

![image](https://user-images.githubusercontent.com/5370251/40147592-8fce38e8-596a-11e8-92e3-e90f887037b1.png)

So if you wanna you can add this text `We'll email you an order confirmation with details and tracking info.` and `Continue Shopping` button.
